name: Test SSH Signed Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test-ssh-push.yml"

jobs:
  test-ssh-signed-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH signing
        env:
          SSH_SIGNING_KEY: ${{ secrets.SSH_SIGNING_KEY }}
        run: |
          # Install the SSH signing key
          mkdir -p ~/.ssh
          echo "$SSH_SIGNING_KEY" > ~/.ssh/signing_key
          chmod 600 ~/.ssh/signing_key
          
          # Get the public key from the private key
          ssh-keygen -y -f ~/.ssh/signing_key > ~/.ssh/signing_key.pub
          
          # Configure git to use SSH signing
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config gpg.format ssh
          git config user.signingkey ~/.ssh/signing_key.pub
          git config commit.gpgsign true
          git config tag.gpgsign true
          
          # Create allowed signers file for verification
          echo "${{ secrets.GIT_USER_EMAIL }} $(cat ~/.ssh/signing_key.pub)" > ~/.ssh/allowed_signers
          git config gpg.ssh.allowedSignersFile ~/.ssh/allowed_signers
          
          # Display the public key (useful for debugging)
          echo "=== SSH Signing Public Key ==="
          cat ~/.ssh/signing_key.pub

      - name: Make test change
        run: |
          TEST_FILE="test-ssh-signed-${{ github.run_id }}-${{ github.run_number }}.txt"
          echo "Test SSH signed push at $(date)" > "$TEST_FILE"
          echo "Run ID: ${{ github.run_id }}" >> "$TEST_FILE"
          echo "Run Number: ${{ github.run_number }}" >> "$TEST_FILE"
          git add "$TEST_FILE"
          git commit -S -m "test: SSH signed commit - run ${{ github.run_number }}"
          
          # Verify the commit was signed
          echo "=== Verifying SSH signature ==="
          git log --show-signature -1

      - name: Push to repository
        run: |
          git push origin main

      - name: Verify push succeeded
        run: |
          echo "Push completed successfully!"
          git log --oneline -n 5

      - name: Clean up test file
        if: always()
        run: |
          TEST_FILE="test-ssh-signed-${{ github.run_id }}-${{ github.run_number }}.txt"
          if [ -f "$TEST_FILE" ]; then
            git rm "$TEST_FILE"
            git commit -S -m "test: cleanup SSH signed test file - run ${{ github.run_number }}"
            git push origin main
          fi