# Windows Debug Memory Tests Workflow
# This workflow runs the Windows debug build with memory leak detection
# It uses scripts/windows-debug-check.ps1 to ensure consistency with local development

name: Windows Debug Memory Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      security_tests_only:
        description: 'Run only security tests'
        required: false
        default: 'false'
        type: boolean

jobs:
  windows-debug-memory:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --ignore-scripts
      
      - name: Run Windows debug build and memory tests
        run: |
          $scriptArgs = @()
          if ('${{ github.event.inputs.security_tests_only }}' -eq 'true') {
            $scriptArgs += '-SecurityTestsOnly'
          }
          
          # Use the existing PowerShell script for consistency
          powershell -ExecutionPolicy Bypass -File scripts/windows-debug-check.ps1 @scriptArgs
        shell: powershell
        env:
          CI: 'true'
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: windows-debug-test-results
          path: |
            test-results/
            *.log
          retention-days: 7